# Caso de negocio clasificación de clientes

## Modelo RFM - Modelo K-Means

## Fase Importación Datos

### Importar librerías

In [184]:
import pandas as pd
import numpy as np

# pandas: librería para el análisis de datos
# numpy: librería para el cálculo numérico

### Definir las bases de datos

In [185]:
df_parques = pd.read_csv('usos_parques_2024_2025.csv')

In [186]:
df_parques2 = pd.read_csv('usos_parques_2024_2025.2.csv')

### Mostrar las bases de datos definidas (filas iniciales)

In [187]:
df_parques.head()

,code_anon,genero,fechanacimiento,fecha,hora,codsede,codproducto,valor_neto,valor_descuento,tarifa,grupo,tipo_venta
0,ID_d91be8edb096,Femenino,1977-01-09,2025-05-25,11.0,721.0,24.0,0.0,4700,TA,Cortesias web 2-Apl,Individual
1,ID_6d1b7b46e8f8,Masculino,1971-12-20,2025-05-25,11.0,722.0,24.0,4800.0,0,TB,NaN,Individual
2,ID_565bd74de162,Masculino,1963-10-28,2025-05-25,8.0,721.0,24.0,21400.0,0,TC,Adulto mayor no afi. parques,Individual
3,ID_ca7d0706f01b,Femenino,2006-03-16,2025-05-25,10.0,723.0,504.0,3100.0,0,TB,NaN,Individual
4,ID_b7edbab69874,Femenino,1988-02-07,2025-05-25,16.0,723.0,504.0,4300.0,0,TC,NaN,Individual

In [188]:
df_parques2.head()

,code_anon,genero,fechanacimiento,fecha,hora,codsede,codproducto,valor_neto,valor_descuento,tarifa,grupo,tipo_venta
0,ID_9301202a1548,Masculino,2014-04-28,2024-01-02,9.0,721.0,24.0,4500.0,0,TA,NaN,Individual
1,ID_7f5174f88b44,Femenino,1985-11-29,2024-01-02,9.0,721.0,24.0,4500.0,0,TA,NaN,Individual
2,ID_06a5d7f57dc2,Masculino,2012-07-21,2024-01-02,13.0,723.0,24.0,4500.0,0,TA,NaN,Individual
3,ID_d7a80202670e,Masculino,1975-07-17,2024-01-02,9.0,721.0,24.0,4500.0,0,TA,NaN,Individual
4,ID_bcf0ee23d281,Masculino,1997-12-23,20240102,11.0,779.0,24.0,6500.0,0,TB,NaN,Individual

### Mostrar las bases de datos definidas (filas finales)

In [189]:
df_parques.tail()

,code_anon,genero,fechanacimiento,fecha,hora,codsede,codproducto,valor_neto,valor_descuento,tarifa,grupo,tipo_venta
79112,ID_dbaa5f243423,Masculino,2004-01-23,06/29/2025,10.0,721.0,24.0,4700.0,0,TA,NaN,Individual
79113,ID_0c06ef8d63ab,Femenino,1997-08-15,20240331,11.0,723.0,24.0,4500.0,0,TA,NaN,individual
79114,ID_14d160a8cc3f,Femenino,1989-04-29,2025-09-16,14.0,723.0,24.0,0.0,4700,TA,Cortesias web 2-Apl,Individual
79115,ID_ce4606680ab6,Masculino,1996-10-07,2024-06-23,14.0,721.0,24.0,30000.0,0,TD,NaN,Individual
79116,ID_61fe2260b2af,Masculino,1985-05-12,2025-03-08,11.0,779.0,24.0,0.0,4200,TA,Cortesias web 2-Apl,Individual

In [190]:
df_parques2.tail()

,code_anon,genero,fechanacimiento,fecha,hora,codsede,codproducto,valor_neto,valor_descuento,tarifa,grupo,tipo_venta
225677,ID_dbaa5f243423,Masculino,2004-01-23,06/29/2025,10.0,721.0,24.0,4700.0,0,TA,NaN,Individual
225678,ID_0c06ef8d63ab,Femenino,1997-08-15,20240331,11.0,723.0,24.0,4500.0,0,TA,NaN,individual
225679,ID_14d160a8cc3f,Femenino,1989-04-29,2025-09-16,14.0,723.0,24.0,0.0,4700,TA,Cortesias web 2-Apl,Individual
225680,ID_ce4606680ab6,Masculino,1996-10-07,2024-06-23,14.0,721.0,24.0,30000.0,0,TD,NaN,Individual
225681,ID_61fe2260b2af,Masculino,1985-05-12,2025-03-08,11.0,779.0,24.0,0.0,4200,TA,Cortesias web 2-Apl,Individual

### Cargar las tablas de código

In [191]:
sedes = pd.read_excel("codigos_sedes_producto.xlsx", sheet_name="Sedes")
productos = pd.read_excel("codigos_sedes_producto.xlsx", sheet_name="Productos")

### Mostrar los códigos cargados

In [192]:
sedes.head()

   codsede                        sede
0      721   Administracion copacabana
1      722  Administracion la estrella
2      723     Administracion Rionegro
3      724      Administracion guatape
4      779  Administracion parque arvi

In [193]:
productos.head()

   codproducto                             strdescripcionproducto
0           24                                        Ing. parque
1          136                                   Ingreso nocturno
2          145                      Brazalete todo parque interno
3          504                                    Eventos Tutucan
4         1109  Paquete Ingreso Nocturno. Aplica Rionegro, Est...

### Mostrar las columnas y características de mi base de datos

In [194]:
df_parques2.info()

<class 'pandas.DataFrame'>
RangeIndex: 225682 entries, 0 to 225681
Data columns (total 12 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   code_anon        225682 non-null  str
 1   genero           225682 non-null  str
 2   fechanacimiento  225682 non-null  str
 3   fecha            225682 non-null  str
 4   hora             225682 non-null  float64
 5   codsede          225682 non-null  float64
 6   codproducto      225682 non-null  float64
 7   valor_neto       225682 non-null  float64
 8   valor_descuento  225682 non-null  int64
 9   tarifa           225682 non-null  str
 10  grupo            95833 non-null   str
 11  tipo_venta       225682 non-null  str
dtypes: float64(4), int64(1), str(7)
memory usage: 20.7 MB

## Fase Limpieza de datos

### Veamos la calidad de los datos de la columna "tarifa" y "tipo_venta"

In [195]:
print(df_parques2["tarifa"].unique())

<StringArray>
[                      'TA',                      ' TB',
                       'TD',                       'TB',
                       'TC',       'ABIERTO AL PÚBLICO',
                       'ta',                      ' TD',
                  ' T  B  ',                       'tc',
 ...
    ' ABIERTO AL   PÚBLICO', '  abierto a  l público  ',
  ' Ab  ierto al Público  ',  '  Abierto al   Publico ',
    'ABIERTO AL PÚ  BLICO ',    ' AB  IERTO AL PÚBLICO',
    'ABIERTO AL PÚBLI  CO ',   'Abierto al Públic  o  ',
   '  abierto al públ  ico', '  Abierto al P  ublico  ']
Length: 415, dtype: str

In [196]:
print(df_parques2["tipo_venta"].unique())

<StringArray>
[      'Individual',   'Individ  ual  ',      'INDIVIDUAL ',
    '  individual ',      ' Individual',     'i  ndividual',
    ' individual  ',       'INDIVIDUAL',       'individual',
      'individual ',
 ...
  '    Empresarial',  '  individ  ual ',   ' Empresarial  ',
   'Empres  arial ', ' EMPRESARIA  L  ',  ' empresaria  l ',
 '  Empresari  al ',   'Emp  resarial ',  '  EMPRE  SARIAL',
    'EMPRES  ARIAL']
Length: 346, dtype: str

### Crear función para limpiar texto

In [197]:
import unicodedata

# unicodedata: librería interna de Python que permite trabajar con caracteres Unicode y realizar operaciones de normalización y eliminación de acentos.

def limpiar_texto(serie):
    # Quitar los espacios sobrantes (espacios internos), normalizar mayúsculas y quitar acentos
    return(serie.astype(str).str.normalize('NFKC').str.strip().str.replace(r'\s+', '', regex=True).str.upper().str.normalize('NFKD').str.encode('ascii', errors='ignore').str.decode('utf-8')).replace(r'ABIERTOALPUBLICO', 'ABIERTO AL PUBLICO', regex=True)
           
           #normalize('NFKC') convierte espacios especiales a su forma canónica, eliminando caracteres redundantes o combinaciones de caracteres que representan el mismo carácter.
           #strip elimina espacios al inicio y al final
           #replace (r'\s+', '', regex=True) elimina todos los espacios internos
           #upper convierte a mayúsculas
           #normalize('NFKD') descompone caracteres acentuados en sus componentes base y marcas diacríticas.
           #encode('ascii', errors='ignore') convierte los caracteres a ASCII, ignorando aquellos que no se pueden representar en ASCII (como acentos).
           #decode('utf-8') convierte los bytes resultantes de la codificación ASCII de nuevo a una cadena de texto en formato UTF-8.

df_parques2["tarifa"] = limpiar_texto(df_parques2["tarifa"])
df_parques2["tipo_venta"] = limpiar_texto(df_parques2["tipo_venta"])

In [198]:
print(df_parques2["tarifa"].unique())

<StringArray>
['TA', 'TB', 'TD', 'TC', 'ABIERTO AL PUBLICO']
Length: 5, dtype: str

In [199]:
print(df_parques2["tipo_venta"].unique())

<StringArray>
['INDIVIDUAL', 'EMPRESARIAL']
Length: 2, dtype: str

### Veamos la calidad de los datos de la columna "fechanacimiento" y "fecha"

In [200]:
df_parques2["fechanacimiento"].head(10)

0    2014-04-28
1    1985-11-29
2    2012-07-21
3    1975-07-17
4    1997-12-23
5    1982-12-08
6    1965-04-16
7    1985-01-25
8    1997-12-23
9    1984-08-23
Name: fechanacimiento, dtype: str

In [201]:
df_parques2["fechanacimiento"].tail(10)

225672    1997-10-02
225673    2009-04-06
225674    2015-02-15
225675    2015-04-14
225676    1975-10-28
225677    2004-01-23
225678    1997-08-15
225679    1989-04-29
225680    1996-10-07
225681    1985-05-12
Name: fechanacimiento, dtype: str

In [202]:
df_parques2["fecha"].head(10)

0    2024-01-02
1    2024-01-02
2    2024-01-02
3    2024-01-02
4      20240102
5    2024-01-02
6    2024-01-02
7    2024-01-02
8    2024-01-02
9    2024-01-02
Name: fecha, dtype: str

In [203]:
df_parques2["fecha"].tail(10)

225672    01/02/2025
225673    2024-02-11
225674    2024-11-26
225675    2025-07-04
225676    2024-07-02
225677    06/29/2025
225678      20240331
225679    2025-09-16
225680    2024-06-23
225681    2025-03-08
Name: fecha, dtype: str

### Crear función para limpiar fecha

In [204]:
# Fecha de nacimiento: fecha de nacimiento del visitante

nacimiento=df_parques2["fechanacimiento"].astype(str).str.strip().str.replace(r'\s+', '-', regex=True)
# astype(str): convierte la columna "fechanacimiento" a tipo de datos cadena (string).
# str.strip(): elimina los espacios en blanco al inicio y al final de cada valor de la columna.
# str.replace(r'\s+', '-', regex=True): reemplaza los espacios internos (uno o más espacios consecutivos) por un guion (-) utilizando una expresión regular.

df_parques2["fechanacimiento"] = pd.to_datetime(nacimiento, format='%Y-%m-%d', errors='coerce')

In [205]:
df_parques2["fechanacimiento"].head(10)

0   2014-04-28
1   1985-11-29
2   2012-07-21
3   1975-07-17
4   1997-12-23
5   1982-12-08
6   1965-04-16
7   1985-01-25
8   1997-12-23
9   1984-08-23
Name: fechanacimiento, dtype: datetime64[us]

In [206]:
df_parques2 = pd.read_csv("usos_parques_2024_2025.2.csv")

In [207]:
df_parques2["fecha"].head(10)

0    2024-01-02
1    2024-01-02
2    2024-01-02
3    2024-01-02
4      20240102
5    2024-01-02
6    2024-01-02
7    2024-01-02
8    2024-01-02
9    2024-01-02
Name: fecha, dtype: str

In [208]:
# Fecha : fecha de la visita al parque

fecha=df_parques2["fecha"].astype(str).str.strip()
# astype(str): convierte la columna "fecha" a tipo de datos cadena (string).
# str.strip(): elimina los espacios en blanco al inicio y al final de cada valor de la columna.

# Para los formatos de 8 digitos consecutivos (YYYYMMDD), se reemplaza por el formato YYYY-MM-DD:

mask8=fecha.str.fullmatch(r'\d{8}')
# mask8: variable que almacena un booleano (True o False) para cada valor de la columna "fecha", indicando si coincide con el patrón de 8 dígitos (YYYYMMDD) utilizando una expresión regular.
# str.fullmatch(r'\d{8}'): verifica si cada valor de la columna "fecha" coincide exactamente con el patrón de 8 dígitos (YYYYMMDD) utilizando una expresión regular.

fecha=fecha.where(~mask8, fecha.str.slice(0, 4) + '-' + fecha.str.slice(4, 6) + '-' + fecha.str.slice(6, 8))
# where(mask8, ...): mantiene los valores de la columna "fecha" que cumplen con la condición de mask8 (coinciden con el patrón de 8 dígitos) y reemplaza los valores que no cumplen con el patrón por una nueva cadena formateada como "YYYY-MM-DD" utilizando slicing para extraer las partes correspondientes del valor original.
#slice(0, 4): extrae los primeros 4 caracteres (año) del valor original.
#slice(4, 6): extrae los siguientes 2 caracteres (mes) del valor original.
#slice(6, 8): extrae los últimos 2 caracteres (día) del valor original.

# Normalizar el dato con formato YYYY-MM-DD, cambiando por guiones a barras (YYYY/MM/DD): 

slash=fecha.str.contains('/', na=False)
# slash: variable que almacena un booleano (True o False) para cada valor de la columna "fecha", indicando si contiene una barra (/).
# str.contains('/', na=False): verifica si cada valor de la columna "fecha" contiene una barra (/).

fecha_final=pd.Series(pd.NaT, index=fecha.index, dtype='datetime64[ns]')
# Las que tienen "/" son MM/DD/YYYY (formato U.S.A.)
fecha_final[slash] = pd.to_datetime(fecha[slash], format='%m/%d/%Y', errors='coerce')
# Las demás son YYYY-MM-DD (formato ISO 8601)
fecha_final[~slash] = pd.to_datetime(fecha[~slash], format='%Y-%m-%d', errors='coerce')

# reemplazamos la columna "fecha" en el DataFrame original con la columna "fecha_final" que contiene los valores normalizados y convertidos a tipo de datos datetime64[ns].
df_parques2["fecha"] = fecha_final

In [209]:
df_parques2["fecha"].value_counts()

fecha
2025-06-29    1797
2024-06-30    1655
2024-01-07    1534
2025-06-22    1508
2025-06-30    1372
              ...
2024-04-22       6
2024-11-24       6
2024-10-21       5
2025-12-14       4
2024-01-22       3
Name: count, Length: 721, dtype: int64

In [210]:
df_parques2["fecha"].head()

0   2024-01-02
1   2024-01-02
2   2024-01-02
3   2024-01-02
4   2024-01-02
Name: fecha, dtype: datetime64[ns]

In [211]:
df_parques2.head()

,code_anon,genero,fechanacimiento,fecha,hora,codsede,codproducto,valor_neto,valor_descuento,tarifa,grupo,tipo_venta
0,ID_9301202a1548,Masculino,2014-04-28,2024-01-02,9.0,721.0,24.0,4500.0,0,TA,NaN,Individual
1,ID_7f5174f88b44,Femenino,1985-11-29,2024-01-02,9.0,721.0,24.0,4500.0,0,TA,NaN,Individual
2,ID_06a5d7f57dc2,Masculino,2012-07-21,2024-01-02,13.0,723.0,24.0,4500.0,0,TA,NaN,Individual
3,ID_d7a80202670e,Masculino,1975-07-17,2024-01-02,9.0,721.0,24.0,4500.0,0,TA,NaN,Individual
4,ID_bcf0ee23d281,Masculino,1997-12-23,2024-01-02,11.0,779.0,24.0,6500.0,0,TB,NaN,Individual